### ISSUE TITLE
Panic: runtime error: slice bounds out of range [34:0]

### ISSUE THREAD

**Issue by rngtng** [waringer/broadlink#1]
Hey hey, thanks for  your awesome go lib! I was able to setup my RM3 mini successfully, but when I start learning I get a `Panic: runtime error`.  Any idea how to fix that?

```
Broadlink RM Toolbox
[01] Device IP: 192.168.178.43
Found 1 device(s)
[00] Wait for learned code.........panic: runtime error: slice bounds out of range [34:0]

goroutine 1 [running]:
_/Users/tobi/Projects/broadlink/broadlink/broadlinkrm.Command(0xbf9598ba00000004, 0x0, 0x0, 0x0, 0xc000040d18, 0x1285280, 0x1, 0x0)
	/Users/tobi/Projects/broadlink/broadlink/broadlinkrm/broadlinkrm.go:157 +0x3b4
main.learn(0x1, 0xc0000a6550, 0x1, 0x1)
	/Users/tobi/Projects/broadlink/broadlink/main.go:177 +0x143
main.main()
	/Users/tobi/Projects/broadlink/broadlink/main.go:62 +0x3a4
```

**Comment by rngtng** [comment]
Btw. compiled with

```
❯ go version
go version go1.13.4 darwin/amd64
```

**Comment by waringer** [comment]
I have looked into it and can't reproduce it here with go 1.13.6 on a CentOS 7 or 1.13.7 on Windows 10 :(
It looks like the device have send a response packet that is too small.
Can you please try it with the verbose parameter again so that more info's about whats happen are logged?

Here a sample from one of my devices:

```
# go run main.go -d -v --ip 192.168.0.10 --learn
Broadlink RM Toolbox
[01] Device type: 2737
[01] Device name: 智能遥控
[01] Device MAC: [xx xx xx xx xx xx]
[01] Device IP: 192.168.0.10
[01] Device authenticated
Found 1 device(s)
[00] Wait for learned code2020/03/22 04:54:21 error packet received
.2020/03/22 04:54:22 error packet received
.2020/03/22 04:54:23 error packet received
.2020/03/22 04:54:24 error packet received
.2020/03/22 04:54:25 error packet received
.2020/03/22 04:54:26 error packet received
.2020/03/22 04:54:27 error packet received
.
[00] Learned code: [26002400481c1539161d171e1735181c171d161d161e151f161d171e161d181d1536171c17000d0500000000]

```

**Comment by rngtng** [comment]
@waringer thanks for quick answer, I tried again in verbose mode:

```
Broadlink RM Toolbox
[01] Device type: 5F36
[01] Device name: 智能遥控
[01] Device MAC: [24 df a7 7a bd 44]
[01] Device IP: 192.168.178.43
[01] Device authenticated
Found 1 device(s)
2020/03/22 12:59:57 error packet received
[00] Wait for learned code2020/03/22 12:59:57 error packet received
.2020/03/22 12:59:58 error packet received
.2020/03/22 12:59:59 error packet received
.2020/03/22 13:00:00 error packet received
.2020/03/22 13:00:01 error packet received
.2020/03/22 13:00:02 error packet received
.2020/03/22 13:00:03 error packet received
.2020/03/22 13:00:04 error packet received
.2020/03/22 13:00:05 error packet received
```

while googling for my type I came across https://github.com/mjg59/python-broadlink/pull/317, probably it's related?  Thx

**Comment by waringer** [comment]
Yes, this makes things clear. Unfortunately i don't have an 0x5F36 device and so can't test this myself.

I have checked in a patch (c042e0bd32a170f6ff4f9fdbff6915e7acddd25c) that should fix this problem. It's adding the additional header and check if the response is long enough to prevent a panic in the future. 

Please try it out and let me know if it's working :)

**Comment by rngtng** [comment]
perfect, works like a charm - thanks a lot!
